spring.application.name=Comp3011_Assignment01


# Configure the environment in which the app runs
# Stores configuration settings used by Spring Boot

# Graceful shutdown is app/server configuration, NOT business logic that belongs in a controller

# At startup, Spring Boot automatically reads application.properties and applies the configured settings
# Here, we configure the embedded server to shutdown gracefully, allowing active requests to complete before the server stops.

server.shutdown=graceful
